In [3]:
import pandas as pd

In [4]:
hotel_df=pd.read_csv('realdata.csv')
hotel_df.head()

   ID             NAME  HOTEL ID     HOTEL NAME   LOCATION  RATING
0   1     Rekha Poudel         1  Hotel Shanker  Kathmandu     3.0
1   2    Renuka Dhakal         1  Hotel Shanker  Kathmandu     4.0
2   3  Rewat Kumar Rai         1  Hotel Shanker  Kathmandu     3.0
3   4   Richa Maharjan         1  Hotel Shanker  Kathmandu     2.0
4   5    Rijan Paudyal         1  Hotel Shanker  Kathmandu     2.0

In [5]:
hotelrating=hotel_df.pivot_table(index=['ID'],columns=['HOTEL NAME'],values='RATING')
hotelrating.head()

HOTEL NAME,Aashirbadh Hitel,Annapurna Banquet Pvt Ltd,Annapurna Hotel Nepal,Apsara Boutique hotel,Avocardo And Orchid Resort,Barewa Durbar Hotel And Banquet,Bhairav Village Farm,Bhaktapur Guest House,Bhaktapur Home Pvt Ltd,Bhaktapur Mibchen Home Stay,...,Summit Hotel,Sun Appartmnt And Guesthouse,Taumdhi Homestay,The Chulo Hotel,Townhall Party Palace And Hotel Peace Garden,Traveller's Village,Welcome Heritage Inn,White Pearl Pokhara,Yara Hotel,Zostel Pokhara
ID,,,,,,,,,,,,,,,,,,,,,
1,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN
2,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
4,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,2.0,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN

In [8]:
corrMatrix=hotelrating.corr()
corrMatrix.head()

HOTEL NAME,Aashirbadh Hitel,Annapurna Banquet Pvt Ltd,Annapurna Hotel Nepal,Apsara Boutique hotel,Avocardo And Orchid Resort,Barewa Durbar Hotel And Banquet,Bhairav Village Farm,Bhaktapur Guest House,Bhaktapur Home Pvt Ltd,Bhaktapur Mibchen Home Stay,...,Summit Hotel,Sun Appartmnt And Guesthouse,Taumdhi Homestay,The Chulo Hotel,Townhall Party Palace And Hotel Peace Garden,Traveller's Village,Welcome Heritage Inn,White Pearl Pokhara,Yara Hotel,Zostel Pokhara
HOTEL NAME,,,,,,,,,,,,,,,,,,,,,
Aashirbadh Hitel,1.0,1.0,-1.0,1.0,NaN,NaN,0.500000,0.866025,-0.500000,0.333333,...,NaN,NaN,0.316228,0.500000,-0.190693,-0.577350,NaN,1.000000,NaN,NaN
Annapurna Banquet Pvt Ltd,1.0,1.0,NaN,NaN,0.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.500000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN
Annapurna Hotel Nepal,-1.0,NaN,1.0,NaN,NaN,NaN,0.333333,NaN,0.188982,NaN,...,NaN,NaN,-1.000000,-0.866025,NaN,NaN,NaN,NaN,NaN,NaN
Apsara Boutique hotel,1.0,NaN,NaN,1.0,-1.0,NaN,NaN,NaN,-1.000000,NaN,...,NaN,NaN,1.000000,NaN,NaN,1.000000,0.866025,NaN,NaN,1.0
Avocardo And Orchid Resort,NaN,0.5,NaN,-1.0,1.0,NaN,NaN,NaN,0.316228,-1.000000,...,NaN,NaN,-1.000000,NaN,NaN,0.158114,NaN,-0.866025,NaN,-1.0